# -*- coding: utf-8 -*-
"""Build the JSON dataset for the NMS Nutrient Ingestor web page.
Reads the authoritative CSV (effects data) + name_map (EN->ZH) -> data.json
"""
import csv, json, sys, os
sys.path.insert(0, os.path.dirname(__file__))
from name_map import MAP, EFFECT, TYPE

CSV = os.path.join(os.path.dirname(__file__), "..", "NMS Nutrient Ingestor - Public - Nutrients.csv")
OUT = os.path.join(os.path.dirname(__file__), "..", "js", "data.js")

def num(s):
    s = s.strip().replace(",", "")
    if s == "": return 0
    try: return float(s)
    except: return 0

rows = list(csv.DictReader(open(CSV, encoding="utf-8")))
items = [r for r in rows if r["Item"].strip() and r["Effect"].strip()]

missing = [r["Item"] for r in items if r["Item"] not in MAP]
eff_missing = [r["Effect"] for r in items if r["Effect"] not in EFFECT]
typ_missing = [r["Type"] for r in items if r["Type"] not in TYPE]
print(f"items={len(items)}  missing_names={len(missing)}  missing_effects={len(set(eff_missing))}  missing_types={len(set(typ_missing))}")
if missing: print("MISSING NAMES:\n", "\n".join(missing))
if set(eff_missing): print("MISSING EFFECTS:", set(eff_missing))
if set(typ_missing): print("MISSING TYPES:", set(typ_missing))

data = []
for r in items:
    mins = int(num(r["Mins"])); secs = int(num(r["Secs"]))
    bonus = num(r["Bonus"])
    total = int(num(r["Total Sec"]))
    bonus_total = num(r["Bonus * Total Sec"])
    data.append({
        "en": r["Item"],
        "zh": MAP.get(r["Item"], r["Item"]),
        "type_en": r["Type"],
        "type": TYPE.get(r["Type"], r["Type"]),
        "effect_en": r["Effect"],
        "effect": EFFECT.get(r["Effect"], r["Effect"]),
        "mins": mins,
        "secs": secs,
        "bonus": bonus,
        "total": total,
        "bonus_total": bonus_total,
    })

# stable sort by bonus_total desc as default
data.sort(key=lambda d: (-d["bonus_total"], d["zh"]))

summary = {
    "count": len(data),
    "types": sorted(set(d["type"] for d in data)),
    "effects": sorted(set(d["effect"] for d in data)),
}
payload = {"summary": summary, "data": data}
os.makedirs(os.path.dirname(OUT), exist_ok=True)
# also keep a plain JSON copy
json.dump(payload, open(os.path.join(os.path.dirname(__file__), "..", "data.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=1)
# write as an inlineable JS global (robust for file:// and any static host)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by tools/build.py — do not edit by hand.\n")
    f.write("window.NMS = ")
    f.write(json.dumps(payload, ensure_ascii=False))
    f.write(";\n")
print("wrote", OUT, os.path.getsize(OUT), "bytes")
