# -*- coding: utf-8 -*-
# English -> Chinese name mapping for NMS Nutrient Ingestor items.
# Source of Chinese terminology: No Man's Sky 中文维基 (nms.huijiwiki.com)
#   - 食用产品 page  (edible products + food raw ingredients)
#   - 原料 / 产品 pages (raw ingredients / products)
# Fish (209) translated from official NMS English names.

MAP = {
# ============ RAW INGREDIENT (57) ============
"Aloe Flesh": "芦荟肉",
"Bone Nuggets": "骨块",
"Cactus Nectar": "仙人掌花蜜",
"Chewy Wires": "韧线",
"Crab 'Apple'": "蟹肉“苹果”",
"Craw Milk": "嗉囊奶",
"Creature Egg": "生物卵",
"Crunchy Wings": "松脆的翅膀",
"Crystal Flesh": "水晶肉",
"Diplo Chunks": "迪普洛块",
"Dirty Meat": "肮脏的肉",
"Feline Liver": "猫科肝",
"Fiendish Roe": "恶魔卵",
"Fireberry": "火莓",
"Foraged Mushrooms": "食用蘑菇",
"Fresh milk": "鲜奶",
"Frozen Tubers": "冷冻块茎",
"Giant Egg": "巨卵",
"Glass Grains": "玻璃谷粒",
"Grahberry": "格拉莓",
"Heptaploid Wheat": "七倍体小麦",
"Hexaberry": "六莓",
"Impulse Beans": "脉冲豆",
"Jade Peas": "玉豌豆",
"Juicy Thorax": "多汁胸腔",
"Kelp Rice": "海藻米",
"Latticed Sinew": "缀合肌腱",
"Leg Meat": "腿肉",
"Leopard-Fruit": "豹纹水果",
"Lumpy Brainstem": "块状脑干",
"Marrow Flesh": "骨髓肉",
"Meat Flakes": "肉薄片",
"Meaty Chunks": "肉块",
"Meaty Wings": "肉翅",
"Non-Toxic Mushrooms": "无毒蘑菇",
"Nourishing Slime": "滋养黏液",
"Offal Sac": "内脏囊",
"Pilgrimberry": "漫游莓",
"ProtoSausage": "原始香肠",
"Pulpy Roots": "浆根",
"Rancid Flesh": "腐肉",
"Raw Steak": "生肉排",
"Regis Grease": "里吉斯油",
"Salty Chunks": "咸手指",
"Scaly Meat": "鳞肉",
"Scooped Innards": "舀出的内脏",
"Sievert Beans": "希沃特豆",
"Silicon Egg": "硅卵",
"Solartillo": "索拉提洛",
"Steamed Vegetables": "清蒸蔬菜",
"Sticky Honey": "粘性蜂蜜",
"Strider Sausage": "水黾香肠",
"Sweetroot": "甜根",
"Syrupy Nectar": "糖浆花蜜",
"Tall Eggs": "高卵",
"Warm Proto-Milk": "温热原型奶",
"Wild Yeast": "野生酵母",

# ---- recipe-only raw ingredients（仅作为配方原料出现，不在 575 物品数据集中，无物品页） ----
"Ancient Bones": "远古骨骼",
"Boiled Flipper": "水煮鱼鳍",
"Brined Flesh": "腌制肉块",
"Chalkscale Nibbler": "粉笔鳞啮鱼",
"Colossal Squid": "巨型鱿鱼",
"Common Sunfish": "普通太阳鱼",
"Delicate Legs": "纤细腿肉",
"Fish Fry": "油炸鱼块",
"Fishy Slab": "鱼板肉",
"Fossilised Biped Legs": "石化双足腿",
"Gas-Worm": "气体蠕虫",
"Giant Whiskerfin": "巨型须鳍鱼",
"Glacier Fish": "冰川鱼",
"Grilled Tentacle": "炙烤触手",
"Helion Bass": "赫利恩鲈",
"Immortal Flatfish": "不朽比目鱼",
"Marine Steak": "海洋牛排",
"Peeled Claws": "去壳蟹钳",
"Poached Worms": "水煮虫",
"Seafood 'Feast'": "海鲜“盛宴”",
"Seared Fillet": "香煎鱼柳",
"Smoked Fish": "熏鱼",
"Snail Fillet": "蜗牛柳肉",
"Steamed Rubber": "蒸橡胶",
"Venemous Triggerfin": "毒扳机鳍",
"Whitebait": "小银鱼",
"Wispscale Darter": "鞭鳞箭鱼",

# ============ EDIBLE PRODUCT (299) ============
"'Apple' Cake of Lost Souls": "苹果失魂蛋糕",
"'Apple' Curiosity": "苹果稀有物",
"'Apple' Ice Cream": "苹果冰淇淋",
"'Apple' Roll": "苹果卷",
"'Legs-in-Pastry'": "酥皮裹腿",
"Abyssal Stew": "深渊炖菜",
"Ambrosial Curse": "甘露诅咒",
"Ambrosial Wonder": "甘露奇观",
"Angelic Fruitcake": "天使水果蛋糕",
"Anomalous Doughnut": "异常甜甜圈",
"Anomalous Jam": "异常的果酱",
"Anomalous Tart": "异常果馅饼",
"Appalling Jam Sponge": "惊人果酱海绵蛋糕",
"Baked Anomaly": "烤制异变体",
"Baked Cheese Tart": "烤芝士果馅饼",
"Bittersweet Cocoa": "甜中带苦的可可",
"Bone Broth": "骨汤",
"Bone Butter": "骨黄油",
"Bone Cheese": "骨芝士",
"Bone Cream": "骨奶油",
"Bone Milk": "骨乳",
"Bread": "面包",
"Briney Delight": "咸味佳肴",
"Briney Rime": "咸霜",
"Bugs-in-a-Blanket": "被裹虫",
"Burning Jam Fluffer": "翻滚果酱泡芙",
"Burning Jam Surprise": "炙热果酱奇味",
"Burning Surprise": "炙热奇味",
"Butter Syrup": "黄油糖浆",
"Cactus Jelly": "仙人掌果冻",
"Cake Batter": "蛋糕面糊",
"Cake of Burning Dread": "炙热恐惧蛋糕",
"Cake of Eternal Sleep": "永恒安眠蛋糕",
"Cake of Glass": "玻璃蛋糕",
"Cake of Sin": "罪恶蛋糕",
"Cake of the Lost": "迷失蛋糕",
"Candied 'Apples'": "蜜渍苹果",
"Caramel Curiosity": "焦糖稀有物",
"Caramel Doughnut": "焦糖甜甜圈",
"Caramel Ice Cream": "焦糖冰淇淋",
"Caramel Tart": "焦糖果馅饼",
"Caramel-Encrusted Cake": "焦糖外皮蛋糕",
"Caramelised Nightmare": "焦糖噩梦",
"Cheese-And-Flesh Stew": "芝士炖肉",
"Cheesy Vegetable Pie": "芝士蔬菜馅饼",
"Chewy 'Dumpling' Stew": "耐嚼炖“饺”",
"Chewy Biscuit": "耐嚼饼干",
"Chewy Organ Pie": "耐嚼内脏馅饼",
"Chocolate Cake": "巧克力蛋糕",
"Chocolate Curiosity": "巧克力稀有物",
"Chocolate Dream": "巧克力梦之味",
"Chocolate Ice Cream": "巧克力冰淇淋",
"Chocolate Oozer": "巧克力溢浆物",
"Choking Monstrosity Cake": "噎人怪物蛋糕",
"Churned Butter": "已搅拌的黄油",
"Clarified Oil": "净化油",
"Cocoa Creams": "可可奶油",
"Cocoa Doughnut": "可可甜甜圈",
"Cocoa Tart": "可可果馅饼",
"Cough Biscuits": "止咳饼干",
"Cream": "奶油",
"Cream Buns": "奶油餐包",
"Cream Curiosity": "奶油稀有物",
"Cream Fingers": "奶油手指",
"Cream of Vegetable Stew": "奶油蔬菜炖汤",
"Creamed Organ Soup": "奶油内脏炖汤",
"Creamy Clouds of Nectar": "花蜜奶油云",
"Creamy Sauce": "奶油酱",
"Creamy Treat": "奶油甜点",
"Crunchy Caramel": "脆焦糖",
"Crystalline Soup": "晶体汤",
"Curdy Cracker": "凝酪饼干",
"Custard Curiosity": "蛋奶稀有物",
"Custard Doughnut": "蛋奶甜甜圈",
"Custard Fancy": "蛋奶小糕点",
"Custard Tart": "蛋奶果馅饼",
"Deathly-Cold Ice Cream": "致命极寒冰淇淋",
"Delicate Meringue": "精致蛋白霜",
"Delicious Vegetable Stew": "美味炖蔬菜",
"Devilled Organs": "辣味炖内脏",
"Doomed Cream Cake": "劫数奶油蛋糕",
"Dough": "面团",
"Earthy Pie": "土香馅饼",
"Enriched Biscuit": "富集饼干",
"Esophageal Surprise": "食管奇味",
"Ever-Boiling Cake": "沸腾蛋糕",
"Ever-burning Jam": "长明的果酱",
"Extra-Fluffy Batter": "超蓬松面糊",
"Extra-Fluffy Cream Cake": "超蓬松奶油蛋糕",
"Fibrous Stew": "纤维炖菜",
"Fiery Vegetable Stew": "辣味炖蔬菜",
"Fire Water": "烈酒",
"Fish Biscuit": "鱼饼干",
"Fish Pie": "鱼肉馅饼",
"Fish and Rice": "鱼米饭",
"Flavoursome Organs": "美味炖内脏",
"Flavoursome Sauce": "美味酱",
"Fleshy Cylinder": "肉圆柱",
"Floral Wafer": "花香威化",
"Fluffy Caramel Delight": "蓬松焦糖小蛋糕",
"Fluffy Throatripper": "蓬松撕喉物",
"Frosted Mire": "霜冻沼泽",
"Fruity Ice Cream": "果味冰淇淋",
"Fruity Pudding": "水果布丁",
"Fungal Omelette": "真菌煎蛋卷",
"Fungal Tart": "真菌果馅饼",
"Furball Jelly": "毛球果冻",
"Gelatinous Goop": "胶质粘稠物",
"Gelatinous Membrane": "胶质薄膜",
"Gelatinous Sponge": "胶质海绵",
"Glittering Honey Cake": "华丽蜂蜜蛋糕",
"Glowing Pie": "发光的馅饼",
"Gooey Butter": "黏腻黄油",
"Gooey Caramel Cake": "黏腻焦糖蛋糕",
"Gooey Chocolate Cake": "黏腻巧克力蛋糕",
"Gooey Custard Fancy": "黏腻蛋奶小糕点",
"Gooey Fruit Surprise": "黏腻水果奇味",
"Gooey Honey Puff": "黏腻蜂蜜泡芙",
"Gooey Mouthburner": "黏腻烫嘴物",
"Gooey ProtoButter": "黏腻原型黄油",
"Gooey ProtoDoughnut": "胶粘原甜甜圈",
"Gooey Screamer": "黏腻尖叫物",
"Grahj'am": "格拉果酱",
"Grilled Fillet": "烤鱼排",
"Gristle Pie": "软骨馅饼",
"Gritty Meat Pie": "粗肉馅饼",
"Haunted Chocolate Dreams": "闹鬼巧克力蛋糕",
"Haunted Fillet": "闹鬼鱼排",
"Haunted Pie": "闹鬼馅饼",
"Haunted Wafer": "闹鬼威化",
"Healthy Wheatblock": "健康麦块",
"Herb-Encrusted Flesh": "药草炖肉",
"Herbal Crunchie": "药草脆块",
"High-Fibre Pie": "高纤维馅饼",
"Honey Butter": "蜂蜜黄油",
"Honey Doughnut": "蜂蜜甜甜圈",
"Honey Ice Cream": "蜂蜜冰淇淋",
"Honey Tart": "蜂蜜馅饼",
"Honey Waffle": "蜂蜜华夫饼",
"Honey-Soaked Fancy": "蜂蜜小糕点",
"Honeybutter Doughnut": "蜂蜜黄油甜甜圈",
"Honied AngelCake": "蜂蜜天使蛋糕",
"Honied Proto-Butter": "蜂蜜原型黄油",
"Honied Proto-Cake": "蜂蜜原型蛋糕",
"Honied Throat-Sticker": "戳喉蜂蜜蛋糕",
"Horrifying Mush": "恐怖蘑菇",
"Horrifying, Gooey Delight": "恐怖黏腻小蛋糕",
"Hybrid Cake": "混合蛋糕",
"Ice Cream": "冰淇淋",
"Iced Screams": "冰冻尖叫",
"Icey Marrow": "冰骨髓",
"Interstellar Curiosity": "星际稀有物",
"Interstellar Fancy": "星际小糕点",
"Itching, Creeping Honey": "惊悚痒痒蜂蜜海绵蛋糕",
"Jam Curiosity": "果酱稀有物",
"Jam Doughnut": "果酱甜甜圈",
"Jam Fluffer": "果酱泡芙",
"Jam Oozers": "果酱溢浆物",
"Jam Tart": "果酱馅饼",
"Jammy Burster": "爆裂果酱",
"Jammy Rounds": "圆块果酱",
"Jellied Eel": "果冻鳗",
"Jellied Fur Tart": "胶冻皮毛果馅饼",
"Jellymeat": "果冻肉",
"Leathery Tart": "皮革果馅饼",
"Lumpen Doughnut": "粗块甜甜圈",
"Marine Pie": "海鲜馅饼",
"Monstrous Custard": "怪物蛋奶酱",
"Monstrous Doughnut": "怪物甜甜圈",
"Monstrous Honey Cake": "怪物蜂蜜蛋糕",
"Most Curious Cake": "最古怪蛋糕",
"Mucal Curiosity": "黏液稀有物",
"Mucal Doughnut": "黏液甜甜圈",
"Muculent Tart": "多黏果馅饼",
"Mushed Root Pie": "根茎糊馅饼",
"Mystery Meat Pie": "谜肉馅饼",
"Mystery Meat Stew": "神秘炖肉",
"Nectar Islands": "花蜜群岛",
"Nectar Sponge Cake": "花蜜海绵蛋糕",
"Nightmare Sausage": "噩梦香肠",
"Nourishing Oozer": "滋养溢浆物",
"Omelette": "煎蛋卷",
"Parasitic Omelette": "寄生物煎蛋卷",
"Partially Liquid Cheese": "充液芝士",
"Pastry": "酥皮点心",
"Perpetual Cake": "永久蛋糕",
"Perpetual Honeycake": "永久蜂蜜蛋糕",
"Perpetual Ice Cream": "永久冰淇淋",
"Perpetual Jam Fluffer": "永久果酱泡芙",
"Pickled Fish": "腌鱼",
"Pie Case": "馅饼盒",
"Pilgrim's Tonic": "朝圣者补剂",
"Pollen Puffball": "花粉泡芙",
"Popping Stew": "爆响炖菜",
"Prickly Curiosity": "刺刺稀有物",
"Primardial Sponge": "原初海绵",
"Processed Meat": "加工肉类",
"Processed Sugar": "加工糖",
"Proteinous Doughnut": "蛋白质甜甜圈",
"Proto-Batter": "原型面糊",
"Proto-Beignet": "原型煎饼",
"Proto-Butter": "原型黄油",
"Proto-Cream": "原型奶油",
"Proto-Oil": "原型型油",
"Proto-Omelette": "原型煎蛋卷",
"Proto-Sausage Pie": "原始香肠馅饼",
"ProtoCheese": "原芝士",
"Purged Ribs": "净化肋排",
"Questionable Biscuit": "可疑饼干",
"Questionably Sweet Cake": "可疑甜蛋糕",
"Refined Flour": "精制面粉",
"Refreshing Drink": "清凉饮料",
"Root Juice": "根茎汁",
"Salt-Laced Honey Cake": "盐饰蜂蜜蛋糕",
"Salty Cruncher": "咸脆块",
"Salty Custard": "咸蛋奶沙司",
"Salty Doughnut": "咸口甜甜圈",
"Salty Juice": "咸汁",
"Salty Platter": "咸味拼盘",
"Salty Surprise": "咸奇味",
"Scorching Sauce": "炙热酱",
"Scrambled Marrow": "炒骨髓",
"Sea's Bounty": "海之丰饶",
"Seafood Stew": "海鲜炖菜",
"Seeping Pie": "渗汁馅饼",
"Shell Puree": "壳泥",
"Simple Biscuit": "简易饼干",
"Slime Pop": "黏液泡泡",
"Smoked Meat": "熏肉",
"Smokey Meat Pie": "熏肉馅饼",
"Soft Custard Fancy": "柔软蛋奶小糕点",
"Soft and Spiky surprise": "柔软多刺奇味",
"Softened Marrow": "软化骨髓",
"Soiled Soup": "土汤",
"Solidified Grease Pie": "凝脂馅饼",
"Spiced 'Apple' Cake": "辛香苹果蛋糕",
"Spiced Ice": "辛香冰淇淋",
"Spicy Fleshballs": "辣味炖肉丸",
"Spikey Tart": "带刺的馅饼",
"Splicer's Delight": "拼接者佳肴",
"Sponge of Ambrosia": "甘露海绵",
"Spore Dunkers": "孢子浸块",
"Squirming Fancy": "蠕动小糕点",
"Starbirth Delight": "星诞小蛋糕",
"Starched Fish": "淀粉鱼",
"Starpollen Surprise": "星花粉奇味",
"Startling Fancy": "惊人小糕点",
"Stellar Custard": "星球蛋奶沙司",
"Stellar Custard Tart": "星球蛋奶馅饼",
"Stellar Ice Cream": "星球冰淇淋",
"Stewed Organs": "炖内脏",
"Sticky Finger": "黏手指",
"Sugar Dough": "糖面团",
"Sweet Cream Dreams": "甜美奶油梦之味",
"Sweet and Salty Puff": "甜咸泡芙",
"Sweetened Butter": "加糖黄油",
"Sweetened Mucous": "加糖黏液",
"Sweetened Proto-Butter": "加糖原型黄油",
"Synthetic Honey": "合成蜂蜜",
"Syrup-Drenched Delight": "糖浆浸渍佳肴",
"Syrupy Batter": "甜味稠面糊",
"Syrupy Caramel Slice": "糖浆焦糖块",
"Syrupy Proto-Butter": "糖浆原型黄油",
"Syrupy Tingler": "糖浆刺痛物",
"Syrupy Viscera": "糖浆内脏",
"Tangy Cheese": "香浓芝士",
"Tangy Organ Surprise": "刺鼻内脏奇味",
"Tangy Vegetable Stew": "刺鼻炖蔬菜",
"The Pie of Knowledge": "知识馅饼",
"The Spawning Tart": "孵化果馅饼",
"The Stellarator": "仿星器",
"The Toothbreaker": "断齿馅饼",
"The Worst Stew": "最差炖菜",
"Thick Meat Stew": "大块炖肉",
"Thick, Sweet Batter": "浓稠甜面糊",
"Tooth Pickers": "剔牙签",
"Tortured Honey Cake": "拷打蜂蜜蛋糕",
"Traditional Cake": "传统蛋糕",
"Unbound Cream Horn": "松散奶油角",
"Unbound Monstrosity": "松散怪物糕",
"Unlovable Jam Turnover": "不溶解果酱三角酥",
"Very Thick Custard": "特厚蛋奶酱",
"Viscous Custard": "粘蛋奶沙司",
"Volatile Chocolate Fancy": "易爆巧克力小糕点",
"Vy'Ice Cream": "VY冰淇淋",
"Wailing Batter": "哀号面糊",
"Wailing Caramel Cake": "哀号焦糖蛋糕",
"Well-Smoked Biscuit": "充分熏制饼干",
"Well-Stirred Stew": "搅拌炖菜",
"Whispering Omelette": "低语煎蛋卷",
"Whole Roast Fish": "整条烤鱼",
"Wild Milk": "野生奶",
"Wriggling Doughnut": "蠕动甜甜圈",
"Wriggling Jam": "蠕动果酱",
"Wriggling Tack": "蠕动钉块",
"Wriggling Tart": "蠕动果馅饼",
"Writhing Jam Puff": "扭动果酱泡芙",
"Writhing, Roiling Batter": "翻腾打滚面糊",
"Xeno-Sponge": "异星海绵",

# ============ FISH (209) ============
"Aberrant Duskfin": "异常暮鳍",
"Abyssal Crab": "深渊蟹",
"Abyssal Horror Egg": "深渊恐怖卵",
"Acidic Pufferfish": "酸性河豚",
"All-Seeing Worm": "全视蠕虫",
"Alpha Squid": "阿尔法乌贼",
"Ancient Irontail": "远古铁尾",
"Anemone Anomaly": "海葵异变体",
"Ash Snail": "灰烬蜗牛",
"Atlantidian Crab": "亚特兰蒂斯蟹",
"Aurora Jellyfish": "极光水母",
"Basalt-Tooth Bloater": "玄武岩齿膨胀鱼",
"Bewitching Candlefish": "魅惑烛鱼",
"Bileworm": "胆汁蠕虫",
"Bitterscale Ray": "苦鳞鳐",
"Black-Eyed Shark": "黑眼鲨",
"Bladdersac": "鳔囊",
"Bleached Bonefish": "白骨鱼",
"Bleached Octopus": "白骨章鱼",
"Blind Titancore": "盲巨核",
"Blistering Eel": "灼热鳗",
"Bloated Eel": "膨胀鳗",
"Blue Ribbontail": "蓝缎尾",
"Boiled Snapper": "煮熟鲷",
"Boiling Shark": "沸腾鲨",
"Brain Eel": "脑鳗",
"Breach Crawler": "破水爬行鱼",
"Brineskipper": "盐水跳鱼",
"Briny Worm": "咸水蠕虫",
"Bulging Snapper": "凸眼鲷",
"Cadmium Pearlcase": "镉珍珠壳",
"Candelabra Octopus": "烛台章鱼",
"Caustic Urchin": "灼蚀海胆",
"Cave Prowler": "洞穴游荡鱼",
"Chalkscale Nibber": "粉笔鳞啄鱼",
"Child of Helios": "赫利俄斯之子",
"Clearwater Skipper": "清水跳鱼",
"Colossal Jawfish": "巨颚鱼",
"Colossal Meltfin": "巨融鳍",
"Colossal Mossback": "巨苔背",
"Colossal Shrimp": "巨虾",
"Common Shimmertail": "常见闪尾",
"Crystal Jelly": "水晶水母",
"Crystalfin Shark": "晶鳍鲨",
"Cyclonic Eel": "旋风鳗",
"Cyclopic Eel": "独眼鳗",
"De-Pressurized Blob": "减压凝胶团",
"Deepwater Angler": "深水鮟鱇",
"Deepwater Minnow": "深水小鲦",
"Depleted Razorjaw": "枯竭刀颚",
"Dragonfish": "龙鱼",
"Electric Eel": "电鳗",
"Emeril Sunstar": "艾梅里尔太阳星",
"Encrusted Worm": "结壳蠕虫",
"Erased Clam": "擦除蚌",
"Evaporating Snail": "蒸发蜗牛",
"Ferrite Bowfin": "铁氧体弓鳍",
"Field's Dartfish": "菲尔德箭鱼",
"Flashfire Eel": "闪火鳗",
"Flourishing Shalefish": "繁盛页岩鱼",
"Fool's Goldfish": "愚人金鱼",
"Forktailed Splicer": "叉尾拼接鱼",
"Fragile Icthyoscale": "脆弱鱼鳞",
"Frostbite Ray": "冻伤鳐",
"Frostscale Trout": "霜鳞鳟",
"Frostshell Clam": "霜壳蚌",
"Frozen Isopod": "冷冻等足虫",
"Frozen Knifejaw": "冷冻刀颚",
"Frozen Whelk": "冷冻蛾螺",
"Fumarole Gulper": "喷气孔吞食鱼",
"Gamma Squid": "伽马乌贼",
"Gas Worm": "气体蠕虫",
"Geno-Prawn": "基因对虾",
"Ghost Skipper": "幽灵跳鱼",
"Ghostfin": "幽灵鳍",
"Giant Hairy Crab": "巨毛蟹",
"Giant Icefin": "巨冰鳍",
"Giant Ray": "巨鳐",
"Giant Sunray": "巨太阳鳐",
"Giant Whiskrerfish": "巨触须鱼",
"Giant Witchfin": "巨魔女鳍",
"Glacier Carp": "冰川鲤",
"Glass Angel": "玻璃天使",
"Glowing Catfish": "发光鲶",
"Golden Jellyfish": "金色水母",
"Golden Urchin": "金色海胆",
"Greater Rocktooth": "大岩齿",
"Green-Ring Octopus": "绿环章鱼",
"Greenscale Bloater": "绿鳞膨胀鱼",
"Helix Sawfish": "螺旋锯鱼",
"Hellion Bass": "恶鬼鲈",
"Hexscale Minnow": "六鳞小鲦",
"Hyper-cockle": "超巨蛤",
"Hypnotic Octopus": "催眠章鱼",
"Ice Darter": "冰箭鱼",
"Iceblood Gulper": "冰血吞食鱼",
"Iceshell Turtle": "冰壳龟",
"Immportal Flatfish": "无门比目鱼",
"Inert Whelk": "惰性蛾螺",
"Inverted Brainfish": "倒置脑鱼",
"Inverted Snapper": "倒置鲷",
"Ionised Clam": "离子化蚌",
"Ionised Oyster": "离子化牡蛎",
"Jelly Prawn": "水母对虾",
"Jelly of the Veil": "薄纱水母",
"Jungle Redfin": "丛林红鳍",
"Lamptip Ray": "灯尖鳐",
"Lavascale Trout": "熔岩鳞鳟",
"Lesser Dustfin": "小尘鳍",
"Leviathan Spawn": "利维坦幼鱼",
"Longjaw Snapper": "长颚鲷",
"Luminescent Coral": "发光珊瑚",
"Magma Shark": "岩浆鲨",
"Mandelbrot Worm": "曼德博蠕虫",
"Mantis Ray": "螳螂鳐",
"Many-Eyed Jellyfish": "多眼水母",
"Many-Mouthed Lunker": "多口巨鱼",
"Marine Glowworm": "海洋发光蠕虫",
"Marrow Shark": "骨髓鲨",
"Megalodon": "巨齿鲨",
"Mellifluous Jellyfish": "甜美水母",
"Metallic Shrimp": "金属虾",
"Midnight Eel": "午夜鳗",
"Mineralised Jellyfish": "矿化水母",
"Mirrorscale Skipper": "镜鳞跳鱼",
"Mist Serpent": "迷雾蛇",
"Moon Turtle": "月龟",
"Mother-of-Quicksilver": "水银之母",
"Mud Crab": "泥蟹",
"Murmurfish": "低语鱼",
"Nautilia": "鹦鹉螺",
"Needlefish": "针鱼",
"Non-Euclidean Flatfish": "非欧几里得比目鱼",
"Nucleic Skipper": "核酸跳鱼",
"Ocean's Star": "海洋之星",
"Oilfin": "油鳍",
"Ossified Deinosuchus": "骨化恐鳄",
"Pale Snowtail": "苍白雪尾",
"Plasmatic Squid": "质体乌贼",
"Polyscale Bloater": "多鳞膨胀鱼",
"Pondskipper": "池塘跳鱼",
"Pressurised Clam": "加压蚌",
"Pulp Urchin": "浆状海胆",
"Pyrefin": "火鳍",
"Quartzshell Crab": "石英壳蟹",
"Radiant Sunfish": "辐射翻车鱼",
"Reef Guardian": "珊瑚礁守卫",
"Reef eel": "礁石鳗",
"Rimescale Snapper": "霜鳞鲷",
"Rockfin": "岩鳍",
"Sac-fish": "囊鱼",
"Saltscale Bloater": "盐鳞膨胀鱼",
"Scorpionfish": "蝎鱼",
"Screaming Crab": "尖叫蟹",
"Sea Cucumber": "海参",
"Sentient Crab": "有感知蟹",
"Shadowfin": "阴影鳍",
"Shalebound Starfish": "页岩束缚海星",
"Shimmering Lashtail": "闪光鞭尾",
"Shrieking Flatfish": "尖叫比目鱼",
"Shrieking Oyster": "尖叫牡蛎",
"Shrieking Venttail": "尖叫喷口尾",
"Silent Angler": "沉默鮟鱇",
"Silicate Crab": "硅酸盐蟹",
"Singing Sea-Snail": "歌唱海蜗牛",
"Solar Roach": "太阳鳈",
"Spiny Starfish": "多刺海星",
"Spotted Protofin": "斑点原鳍",
"Spratfin": "玉筋鱼鳍",
"Stargazer": "星眼鱼",
"Starshell Crab": "星壳蟹",
"Stonescale Shark": "石鳞鲨",
"Sulphurfish": "硫磺鱼",
"Sunspine Basker": "日棘晒阳鱼",
"Sunspot Eel": "日斑鳗",
"Sweeperfish": "清扫鱼",
"Sweetwater Minnow": "淡水小鲦",
"Tendrilla": "触丝鱼",
"Thawed Diamondfin": "解冻钻石鳍",
"The Angler": "鮟鱇",
"The Hunter Below": "下方猎手",
"The Lunker": "巨鱼",
"The Maw of Titan": "巨神之口",
"Thunderfin": "雷鳍",
"Tiny Scuttlefish": "小梭鱼",
"Titanworm Larva": "泰坦蠕虫幼虫",
"Toxic Jelly": "毒水母",
"Toxic Stonefish": "毒石头鱼",
"Translucent Gulper": "半透明吞食鱼",
"Twilight Cavefish": "黄昏洞穴鱼",
"Twisted Gulper": "扭曲吞食鱼",
"Vampire Squid": "吸血鬼乌贼",
"Vapourfin": "蒸汽鳍",
"Vectorfin": "矢量鳍",
"Venomouos Triggerfin": "毒扳机鳍",
"Venomtooth Wriggler": "毒齿扭动鱼",
"Viper Eel": "蝰蛇鳗",
"Void Squid": "虚空乌贼",
"Wandering Kelpfin": "游荡海藻鳍",
"Wandering Shellback": "游荡壳背",
"Warden Eel": "守卫鳗",
"Warty Frogfish": "疣状蛙鱼",
"Waspfish": "黄蜂鱼",
"Weltscale Clam": "荨麻疹鳞蚌",
"Whipscale Darter": "鞭鳞箭鱼",
"Whispering Bonefish": "低语骨鱼",
"Whispering Jelly": "低语水母",
"Wrackjaw": "残骸颚",
"Writhing Brainworm": "扭动脑蠕虫",

# ============ MISC (10) ============
"Carbon Nanotubes": "碳纳米管",
"Creature Pellets": "生物颗粒",
"Flesh Rope": "肉绳",
"Fossilised [Something]": "化石[某物]",
"GekNip": "GekNip",
"Hadal Core": "深渊核心",
"Hypnotic Eye": "催眠之眼",
"Juicy Grub": "多汁蛆虫",
"Larval Core": "幼虫核心",
"Nip Nip Buds": "吸吸幼芽",

# ============ RECIPE INGREDIENTS (合成公式 raw components) ============
# Chinese names looked up from the NMS wiki (nms.huijiwiki.com / community).
# These appear as ingredients in other items' crafting recipes ({{Cook}}).
"Carbon": "碳",
"Condensed Carbon": "浓缩碳",
"Salt": "盐",
"Lubricant": "润滑剂",
"Microprocessor": "微处理器",
"Chromatic Metal": "有色金属",
"Gamma Root": "伽马根",
"Frost Crystal": "冰霜水晶",
"Star Bulb": "星辰朵",
"Solanium": "日光茄",
"Faecium": "屎球菌",
"Fungal Mould": "真菌霉",
"Mordite": "咬噬物",
"Marrow Bulb": "骨髓球",
"Kelp Sac": "海藻囊",
"Cactus Flesh": "仙人掌肉",
"Mollusc Flesh": "贝类肉",
"Partially-Liquid Cheese": "半液态奶酪",
"Edible Chum": "可食鱼饵",
"Assorted Roe": "混合鱼卵",
"Any other cooked seafood": "其他熟食海鲜",
"Swift Leg Bones": "疾腿骨",
"NipNip Buds": "吸吸幼芽",
"Fish": "鱼",
}

# English effect -> Chinese
EFFECT = {
"% Breathing Efficiency": "呼吸效率",
"% Cold Resistance": "寒冷抗性",
"% Fauna Analysis Rewards": "动物分析奖励",
"% Flora Analysis Rewards": "植物分析奖励",
"% Hazard Protection Battery": "危险防护电池",
"% Heat Resistance": "炎热抗性",
"% Jetpack Tanks": "喷气背包储气罐",
"% Life Support Tanks": "生命维持储气罐",
"% Mineral Analysis Rewards": "矿物分析奖励",
"% Mining Speed": "采矿速度",
"% Radiation Resistance": "辐射抗性",
"% Recharge Time": "充能时间",
"% Resources Mined": "开采资源量",
"% Shield Strength": "护盾强度",
"% Solar Panel Power": "太阳能板功率",
"% Sprint Distance": "冲刺距离",
"% Sprint Recovery Time": "冲刺恢复时间",
"% Toxic Resistance": "毒素抗性",
"% Unspecified": "未指明",
"Words Translated": "翻译词数",
}

# English type -> Chinese
TYPE = {
"Edible Product": "食用产品",
"Fish": "鱼",
"Raw Ingredient": "原料",
"Horrific Sample": "恐怖样本",
"Crafted Technology Component": "制造的技术部件",
"Compressed Nutrients": "压缩营养物",
"Intestinal Fragment": "肠段碎片",
"Fossil": "化石",
"Trade commodity": "贸易商品",
"Vile Larva": "恶臭幼虫",
"Monstrosity": "怪物",
"Medicinal Substance": "药用物质",
}
